name: 'Run Go Tests'
description: 'Run Go tests with boilerplate setup'
inputs:
  go-version:
    description: 'Go version to use'
    required: true
  module-path:
    description: 'Module directory path'
    required: true
  test-args:
    description: 'Arguments to pass to go test'
    required: true
  timeout:
    description: 'Test timeout'
    required: false
    default: '10m'
  build-tags:
    description: 'Build tags'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true

    - name: Run tests
      working-directory: ${{ inputs.module-path }}
      shell: bash
      run: |
        go test -v -count=1 -shuffle=on -timeout='${{ inputs.timeout || '10m' }}' \
          ${{ inputs.build-tags && format('-tags=''{0}'' ', inputs.build-tags) || '' }} \
          ${{ inputs.test-args }} ./...