name: Build

permissions: {} # no need for any permissions

on:
  workflow_call:
    inputs:
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 5
        required: false
        type: number
      buildTags:
        description: 'Go build tags'
        default: ''
        required: false
        type: string

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes || 5) }}
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build -o=/dev/null ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} ./...

      - name: Go Compile Tests
        run: go test -exec=/bin/true ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} ./...
