name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 14 * * 6' # run each Saturday at 2pm UTC
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  vuln:
    uses: ./.github/workflows/vuln.yml
