name: CI

permissions:
  contents: write # to update coverage report on the wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 14 * * 6' # run each Saturday at 2pm UTC
  workflow_dispatch:
  workflow_call:
    inputs:
      buildJobTimeoutMinutes:
        description: 'Build job timeout in minutes'
        required: false
        type: number
      buildTags:
        description: 'Go build tags'
        required: false
        type: string
      lintJobTimeoutMinutes:
        description: 'Lint job timeout in minutes'
        required: false
        type: number
      golangciLintTimeout:
        description: 'Value to pass to golangci-lint --timeout'
        required: false
        type: string
      shortTestTimeoutMinutes:
        description: 'Timeout for short tests in minutes'
        default: 5
        required: false
        type: number
      short1CpuTestTimeoutMinutes:
        description: 'Timeout for short 1-cpu tests in minutes'
        default: 5
        required: false
        type: number
      shortRaceTestTimeoutMinutes:
        description: 'Timeout for short race tests in minutes'
        default: 10
        required: false
        type: number
      fullTestTimeoutMinutes:
        description: 'Timeout for full tests in minutes'
        default: 10
        required: false
        type: number
      full1CpuTestTimeoutMinutes:
        description: 'Timeout for full 1-cpu tests in minutes'
        default: 10
        required: false
        type: number
      fullRaceTestTimeoutMinutes:
        description: 'Timeout for full race tests in minutes'
        default: 15
        required: false
        type: number
      vulnJobTimeoutMinutes:
        description: 'Vuln job timeout in minutes'
        required: false
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      jobTimeoutMinutes: ${{ inputs.buildJobTimeoutMinutes || 5 }}
      buildTags: ${{ inputs.buildTags }}
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      jobTimeoutMinutes: ${{ inputs.lintJobTimeoutMinutes || 5 }}
      golangciLintTimeout: ${{ inputs.golangciLintTimeout }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      buildTags: ${{ inputs.buildTags }}
      shortTimeoutMinutes: ${{ inputs.shortTestTimeoutMinutes || 5 }}
      short1CpuTimeoutMinutes: ${{ inputs.short1CpuTestTimeoutMinutes || 5 }}
      shortRaceTimeoutMinutes: ${{ inputs.shortRaceTestTimeoutMinutes || 10 }}
      fullTimeoutMinutes: ${{ inputs.fullTestTimeoutMinutes || 10 }}
      full1CpuTimeoutMinutes: ${{ inputs.full1CpuTestTimeoutMinutes || 10 }}
      fullRaceTimeoutMinutes: ${{ inputs.fullRaceTestTimeoutMinutes || 15 }}
  vuln:
    uses: ./.github/workflows/vuln.yml
    with:
      jobTimeoutMinutes: ${{ inputs.vulnJobTimeoutMinutes || 5 }}
