name: lint

permissions: {} # no need for any permissions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 14 * * 6' # run each Saturday at 2pm UTC
  workflow_call:
    inputs:
      groupSuffix:
        description: 'Concurrency group suffix to allow multiple jobs'
        required: false
        type: string
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        required: false
        type: number
      golangciLintTimeout:
        description: 'Value to pass to golangci-lint --timeout'
        required: false
        type: string
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ inputs.groupSuffix }}
  cancel-in-progress: true

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes || 10) }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Goimports Check
        uses: DarthBenro008/goimports-check-action@v0.1.0

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Golangci-Lint
        uses: golangci/golangci-lint-action@v7

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Lint
        uses: golangci/golangci-lint-action@v5.0.0
        with:
          version: latest
          args: --timeout ${{ inputs.golangciLintTimeout || '5m' }}

      - name: Go Vet
        run: go vet ./...
