name: Lint

permissions: {} # no need for any permissions

on:
  workflow_call:
    inputs:
      groupSuffix:
        description: 'Concurrency group suffix to allow multiple jobs'
        default: ''
        required: false
        type: string
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 10
        required: false
        type: number
      golangciLintTimeout:
        description: 'Value to pass to golangci-lint --timeout'
        default: '5m'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ inputs.groupSuffix }}
  cancel-in-progress: true

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes) }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Imports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          goimports -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Golangci-Lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout ${{ inputs.golangciLintTimeout }}
