name: release
  
permissions:
    contents: write

on:
  workflow_call:
    inputs:
      publishDocs:
        description: 'Publish docs to pkg.go.dev'
        required: false
        type: boolean
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  run:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout with tags
        run: git fetch --prune --unshallow --tags

      - name: Create release
        run: |
          sed -rn -e '/^## \[[^]]+\] - [0-9]{4}(-[0-9]{2}){2}/{ :l; p; n; /^(## |\[[^]]+\]: http)/q; bl; }' <./CHANGELOG.md >release-changelog.tmp
          head -1 release-changelog.tmp | sed -r -e 's/^## \[([^]]+)\].*$/v\1/' >release-tag.tmp
          tag="$(cat release-tag.tmp)"
          if git rev-parse -q --verify --end-of-options "$tag"; then echo "tag '$tag' already exists!"; false; fi
          echo '${{ secrets.GITHUB_TOKEN }}' | gh auth login --with-token
          gh release create "$tag" -t "$tag" -F release-changelog.tmp

      - name: Ping pkg.go.dev
        if: ${{ inputs.publishDocs }}
        run: |
          tag="$(cat release-tag.tmp)"
          mod="$(go list -m)
          curl --show-error --fail -w "HTTP %{http_code}\n" -o - "https://pkg.go.dev/fetch/$mod@$tag" \
            --connect-timeout 5 \
            --max-time 10 \
            --retry 10 \
            --retry-delay 30 \
            --retry-max-time 600 \
            -X 'POST' \
            -H 'authority: pkg.go.dev' \
            -H 'content-length: 0' \
            -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36' \
            -H 'sec-ch-ua-platform: "macOS"' \
            -H 'accept: */*' \
            -H 'origin: https://pkg.go.dev' \
            -H 'sec-fetch-site: same-origin' \
            -H 'sec-fetch-mode: cors' \
            -H 'sec-fetch-dest: empty' \
            -H "referer: https://pkg.go.dev/$mod@$tag" \
            -H 'accept-language: en,en-GB;q=0.9,en-US;q=0.8' \
            --compressed
