name: Test

permissions:
  contents: write # to update coverage report on the wiki

on:
  workflow_call:
    inputs:
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 15
        required: false
        type: number
      buildTags:
        description: 'Build tags to use.'
        default: ''
        required: false
        type: string
      shortTimeoutMinutes:
        description: 'Timeout for short tests in minutes'
        default: 5
        required: false
        type: number
      short1CpuTimeoutMinutes:
        description: 'Timeout for short 1-cpu tests in minutes'
        default: 5
        required: false
        type: number
      shortRaceTimeoutMinutes:
        description: 'Timeout for short race tests in minutes'
        default: 10
        required: false
        type: number
      fullTimeoutMinutes:
        description: 'Timeout for full tests in minutes'
        default: 10
        required: false
        type: number
      full1CpuTimeoutMinutes:
        description: 'Timeout for full 1-cpu tests in minutes'
        default: 10
        required: false
        type: number
      fullRaceTimeoutMinutes:
        description: 'Timeout for full race tests in minutes'
        default: 15
        required: false
        type: number

jobs:
  discover-modules:
    uses: ./.github/workflows/modules.yml

  calculate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.calc.outputs.matrix }}
    steps:
      - name: Calculate test matrix with job timeouts
        id: calc
        run: |
          source_matrix='[
            { "type": "short", "name": "default", "args": "-short", "timeoutMinutes": ${{ inputs.shortTimeoutMinutes }} },
            { "type": "short", "name": "1cpu", "args": "-short -cpu 1", "timeoutMinutes": ${{ inputs.short1CpuTimeoutMinutes }} },
            { "type": "short", "name": "race", "args": "-short -race", "timeoutMinutes": ${{ inputs.shortRaceTimeoutMinutes }} },
            { "type": "full", "name": "default", "args": "-bench=. -benchtime=1x -coverprofile=coverage.txt -coverpkg=./...", "timeoutMinutes": ${{ inputs.fullTimeoutMinutes }} },
            { "type": "full", "name": "1cpu", "args": "-bench=. -benchtime=1x -cpu 1", "timeoutMinutes": ${{ inputs.full1CpuTimeoutMinutes }} },
            { "type": "full", "name": "race", "args": "-race -bench=. -benchtime=1x", "timeoutMinutes": ${{ inputs.fullRaceTimeoutMinutes }} }
          ]'
          echo -n "matrix=" >> $GITHUB_OUTPUT
          echo "$source_matrix" | jq 'map(. + {jobTimeoutMinutes: (.timeoutMinutes + 5)})' >> $GITHUB_OUTPUT

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [discover-modules, calculate-matrix]
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']
        module: ${{ fromJSON(needs.discover-modules.outputs.modules) }}
        test-config: ${{ fromJSON(needs.calculate-matrix.outputs.matrix) }}

    steps:
      - name: Run tests
        uses: ./.github/actions/run-go-tests
        with:
          go-version: ${{ matrix.go }}
          module-path: ${{ matrix.module }}
          test-args: ${{ matrix.test-config.args }}
          timeout: ${{ matrix.test-config.timeoutMinutes }}m
          build-tags: ${{ inputs.buildTags }}

      - name: Update coverage report
        if: ${{ matrix.go == 'stable' && matrix.module == '.' && matrix.test-config.type == 'full' && matrix.test-config.name == 'default' && github.event_name == 'push' }}
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: ${{ matrix.module }}/coverage.txt
          amend: true
