name: Test

permissions:
  contents: write # to update coverage report on the wiki

on:
  workflow_call:
    inputs:
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 15
        required: false
        type: number
      buildTags:
        description: 'Build tags to use.'
        default: ''
        required: false
        type: string
      goTestTimeout:
        description: 'Value to pass to go test -timeout'
        default: '10m'
        required: false
        type: string

jobs:
  discover-modules:
    uses: ./.github/workflows/modules.yml

  run:
    name: Test
    runs-on: ubuntu-latest
    needs: discover-modules
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes || 15) }}
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']
        module: ${{ fromJSON(needs.discover-modules.outputs.modules) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Go Test (short)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -short ./...

      - name: Go Test (short, 1 cpu)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -short -cpu 1 ./...

      - name: Go Test (short, race)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -short -race ./...

      - name: Go Test (full, benchmarks, coverage)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -bench=. -benchtime=1x -coverprofile=coverage.txt -coverpkg=./... ./...

      - name: Go Test (full, benchmarks, 1 cpu)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -bench=. -benchtime=1x -cpu 1 ./...

      - name: Go Test (full, benchmarks, race)
        working-directory: ${{ matrix.module }}
        run: |
          go test -v -count=1 -shuffle=on -timeout='${{ inputs.goTestTimeout || '10m' }}' \
             ${{ inputs.buildTags && format('-tags=''{0}'' ', inputs.buildTags) || '' }} \
             -race -bench=. -benchtime=1x ./...

      - name: Update coverage report
        if: ${{ matrix.go == 'stable' && matrix.module == '.' && github.event_name == 'push' }}
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: ${{ matrix.module }}/coverage.txt
          amend: true
