name: test

permissions: {} # no need any permissions

on:
  workflow_call:

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Run tests
        run: go test -v -count=1 -race -shuffle=on ./...
