name: Vuln

permissions: {} # no need for any permissions

on:
  workflow_call:
    inputs:
      groupSuffix:
        description: 'Concurrency group suffix to allow multiple jobs'
        default: ''
        required: false
        type: string
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 5
        required: false
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ inputs.groupSuffix }}
  cancel-in-progress: true

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes) }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...
