name: vuln

permissions: {} # no need for any permissions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 14 * * 6' # run each Saturday at 2pm UTC
  workflow_call:
    inputs:
      groupSuffix:
        description: 'Concurrency group suffix to allow multiple jobs'
        required: false
        type: string
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        required: false
        type: number
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ inputs.groupSuffix }}
  cancel-in-progress: true

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes || 5) }}
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...
