name: Vuln

permissions: {} # no need for any permissions

on:
  workflow_call:
    inputs:
      jobTimeoutMinutes:
        description: 'Overall job timeout in minutes'
        default: 5
        required: false
        type: number

jobs:
  discover-modules:
    uses: ./.github/workflows/modules.yml

  vuln:
    name: Vuln
    runs-on: ubuntu-latest
    needs: discover-modules
    timeout-minutes: ${{ fromJSON(inputs.jobTimeoutMinutes || 5) }}
    strategy:
      fail-fast: true
      matrix:
        module: ${{ fromJSON(needs.discover-modules.outputs.modules) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        working-directory: ${{ matrix.module }}
        run: govulncheck -test ./...
